sudo: true
language: node_js
node_js:
  - "10"
script:
  - npm ci
  - npm run lint
deploy:
  - provider: script
    skip_cleanup: true
    before_deploy:
      - curl -sf https://up.apex.sh/install | sh
      - up upgrade
    script: ./deploy.sh
    on:
      branch: master
